# This is a basic workflow to help you get started with Actions

name: 打包应用并上传服务器

# Controls when the action will run.
on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 获取package信息
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      # 安装node
      - name: 安装node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
          registry-url: https://registry.npmjs.org

      - name: 发布到NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
